import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'EN' | 'BM' | 'DE';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  EN: {
    login: 'Login',
    userId: 'User ID',
    password: 'Password',
    hub: 'Command Center',
    stockTake: 'Stock Take',
    batteryTracking: 'Battery Tracking',
    qualityAssurance: 'Quality Assurance',
    back: 'Back',
    notCounted: 'Not Counted',
    counted: 'Counted',
    verified: 'Verified',
    role: 'Role',
    zoneProgress: 'Zone Progress',
    search: 'Search Part No / Material...',
    welcome: 'Welcome',
    selectModule: 'Select a module to continue',
    manageParts: 'Manage parts inventory, counts, and verification across zones.',
    trackBattery: 'Track battery statuses, locations, and lifecycle.',
    performQA: 'Perform QA inspections and log discrepancies.',
    overallProgress: 'Overall progress',
    trackedToday: 'Tracked today',
    today: 'Today',
    yourModules: 'Your modules',
    uploadRawCsv: 'Upload Raw CSV Data',
    uploadRawCsvDesc: 'Auto-upload CSV files directly to Supabase. Any new columns are automatically added.',
    selectData: 'Select Data',
    loggedInAs: 'Logged in as',
    logout: 'Logout',
    view: 'VIEW',
    liveData: 'Live Data',
    items: 'Items',
    ready: 'Ready',
    pending: 'Pending',
    zones: 'Zones',
    progress: 'Progress',
    userProgress: 'User Progress',
    viewCheckPart: 'View Check Part Data (Remarks)',
    adminSettingsCsv: 'Admin Settings (CSV Upload)',
    confirmLogout: 'Are you sure you want to log out?',
    cancel: 'Cancel',
    rememberMe: 'Remember me',
    adminSettings: 'Admin Settings',
    masterPartsDbUpload: 'Master Parts Database Upload',
    uploadDesc: 'Upload a .xlsx file to refresh the parts inventory.',
    fileRequirements: 'File Requirements:',
    formatLabel: 'Format: .csv, .xlsx, or .xls',
    requiredColumns: 'Required Columns: Material, Part Name (or Part No), Storage Bin (or Location)',
    extraColumns: 'All extra columns will automatically be saved into the database\'s metadata field!',
    assignZone: 'Assign to Zone:',
    uploadingBtn: 'Uploading...',
    selectUploadBtn: 'Select & Upload CSV / Excel File',
    listView: 'List View',
    loadingParts: 'Loading parts...',
    material: 'Material',
    partNo: 'Part No',
    zone: 'Zone',
    location: 'Location',
    status: 'Status',
    action: 'Action',
    viewEdit: 'View / Edit',
    noParts: 'No parts found.',
    countingInterface: 'Counting Interface',
    partInformation: 'Part Information',
    lock: 'Lock',
    adminUnlockBtn: 'Admin Unlock',
    counterInputs: 'Counter Inputs',
    box: 'Box',
    boxTotal: 'Box Total:',
    verifierInput: 'Verifier Input',
    recountValue: 'Recount Value',
    enterRecount: 'Enter recount total...',
    recountWarning: '* Recount value must NOT equal the Box Total.',
    saveData: 'Save Data',
    saving: 'Saving...',
    userProgressReport: 'User Progress Report',
    downloadPdf: 'Download PDF',
    progressSummary: 'VGM CKD - Progress Summary',
    recentActivity: 'Recent Activity',
    loadingData: 'Loading data...',
    lastUpdated: 'Last Updated',
    showingLatestUpdates: 'Report generated on',
    dataRefreshed: 'Data refreshed successfully!',
    downloadCsv: 'Download CSV',
    userSummary: 'User Summary',
    name: 'Name',
    lastLogin: 'Last Login',
    lastLogout: 'Last Logout',
    filterByStatus: 'Filter by Status',
    filterByLocation: 'Filter by Location',
    allStatuses: 'All Statuses',
    allLocations: 'All Locations',
    generatedOn: 'Generated on',
    verifiedBy: 'Verified By',
    itemDetails: 'Item Details',
    edit: 'Edit',
    unlock: 'Unlock',
    locked: 'Locked',
    save: 'Save',
    itemInformation: 'Item Information',
    countData: 'Count Data',
    verifyNow: 'Verify Now',
    addRemarkPlaceholder: 'Click to add remark...',
    // Redesign
    refresh: 'Refresh',
    live: 'Live',
    dashboard: 'Dashboard',
    admin: 'Admin',
    users: 'Users',
    all: 'All',
    total: 'Total',
    qty: 'Qty',
    soon: 'Soon',
    noData: 'No data',
    checkPart: 'Check Part',
    partsFlagged: 'parts flagged for a second look',
    partsVerified: 'Parts verified',
    partsToCheck: 'Parts to check',
    adminTools: 'Admin tools',
    uploadParts: 'Upload parts',
    tapZoneHint: 'Tap a zone to start counting',
    showingRange: 'Showing {range} of {total}',
    zoneNotUploaded: 'No parts uploaded for {zone} yet. An admin can upload them in Admin → Parts upload.',
    latestUpload: 'Latest upload',
    oldUpload: 'Old upload',
    nextBoxHint: 'Next box appears once this one is filled',
    recount: 'Recount',
    verifierOnly: 'Verifier only',
    matchesBoxTotal: 'Matches box total ({n})',
    differsBoxTotal: 'Differs from box total ({n})',
    enterCountToSave: 'Enter a count to save',
    forgotPassword: 'Forgot password? Ask your admin.',
    installApp: 'Install app',
    loginTagline: 'CKD Logistic Department — plant inventory for B17, B22, LOMA and B22 SEQ.',
    headline1: 'Count.',
    headline2: 'Check.',
    headline3: 'Verify.',
    // Parts upload
    partsUploadTab: 'Parts upload',
    zoneLocksNote: 'A zone locks once it has data.',
    selectFile: 'Select file',
    fileTypesHint: '.csv, .xlsx or .xls · max 15MB',
    hasData: 'Has data',
    emptyReady: 'Empty · ready',
    checkingZone: 'Checking zone status...',
    readingFile: 'Reading file...',
    previewTitle: 'Check before uploading',
    rowsFound: '{n} rows',
    columnsFound: 'Columns found',
    missingColumns: 'Missing columns',
    missingRequired: 'Missing {cols} — the parts list for this zone needs it.',
    missingBoxes: 'No Box columns — counters won\'t be able to enter counts.',
    missingRecount: 'No Recount column — verifiers won\'t have a recount box.',
    zoneMismatch: 'The file name says {fileZone}, but you selected {selZone}. Where should it go?',
    targetLocked: '{zone} already has data. Unlock & clear it first, or choose another zone.',
    uploadTo: 'Upload to {zone}',
    chooseOtherFile: 'Choose another file',
    fileTableNote: 'The table is generated from your file\'s column headers.',
    fileNameNote: 'Name the file with its zone (e.g. VGM 2026 - B22.xlsx) and it is suggested automatically.',
    zoneIsLocked: '{zone} is locked',
    lockedExplain: 'This zone already has a database table. To upload a new master file, unlock and clear it first.',
    unlockClear: 'Unlock & clear zone',
    unlockTitle: 'Unlock & clear {zone}',
    unlockWarn: 'This permanently deletes every part, count and remark in {zone}. A backup file downloads first.',
    typeToConfirm: 'Type {code} to confirm',
    backupAndClear: 'Download backup & clear',
    backingUp: 'Saving backup...',
    backupFailed: 'Backup failed, so nothing was deleted: {err}',
    zoneCleared: '{zone} was cleared. Backup saved as {file}.',
    offline: 'Offline',
    toSync: '{n} to sync',
    syncedCounts: 'Synced {n} saved counts',
    syncFailed: '{n} could not be saved — tap to retry',
    savedOffline: 'No signal — saved on this phone. It will sync when you are back online.',
    showingCached: 'No signal — showing the data loaded earlier.',
    lastUpdate: 'Last update'
  },
  BM: {
    login: 'Log Masuk',
    userId: 'ID Pengguna',
    password: 'Kata Laluan',
    hub: 'Pusat Arahan',
    stockTake: 'Kiraan Stok',
    batteryTracking: 'Penjejakan Bateri',
    qualityAssurance: 'Jaminan Kualiti',
    back: 'Kembali',
    notCounted: 'Belum Dikira',
    counted: 'Telah Dikira',
    verified: 'Disahkan',
    role: 'Peranan',
    zoneProgress: 'Kemajuan Zon',
    search: 'Cari No Bahagian / Bahan...',
    welcome: 'Selamat Datang',
    selectModule: 'Pilih modul untuk meneruskan',
    manageParts: 'Urus inventori bahagian, kiraan, dan pengesahan merentas zon.',
    trackBattery: 'Jejak status bateri, lokasi, dan kitaran hayat.',
    performQA: 'Jalankan pemeriksaan QA dan rekod percanggahan.',
    overallProgress: 'Kemajuan keseluruhan',
    trackedToday: 'Dijejak hari ini',
    today: 'Hari ini',
    yourModules: 'Modul anda',
    uploadRawCsv: 'Muat Naik Data CSV',
    uploadRawCsvDesc: 'Muat naik fail CSV terus ke Supabase. Lajur baharu ditambah secara automatik.',
    selectData: 'Pilih Data',
    loggedInAs: 'Log masuk sebagai',
    logout: 'Log Keluar',
    view: 'PANDANGAN',
    liveData: 'Data Langsung',
    items: 'Item',
    ready: 'Sedia',
    pending: 'Menunggu',
    zones: 'Zon',
    progress: 'Kemajuan',
    userProgress: 'Kemajuan Pengguna',
    viewCheckPart: 'Lihat Data Semak Bahagian (Catatan)',
    adminSettingsCsv: 'Tetapan Admin (Muat Naik CSV)',
    confirmLogout: 'Adakah anda pasti mahu log keluar?',
    cancel: 'Batal',
    rememberMe: 'Ingat saya',
    adminSettings: 'Tetapan Admin',
    masterPartsDbUpload: 'Muat Naik Pangkalan Data Bahagian Utama',
    uploadDesc: 'Muat naik fail .xlsx untuk menyegarkan inventori bahagian.',
    fileRequirements: 'Keperluan Fail:',
    formatLabel: 'Format: .csv, .xlsx, atau .xls',
    requiredColumns: 'Lajur Diperlukan: Bahan, Nama Bahagian (atau No Bahagian), Tong Penyimpanan (atau Lokasi)',
    extraColumns: 'Semua lajur tambahan akan disimpan secara automatik ke dalam medan metadata pangkalan data!',
    assignZone: 'Tugaskan kepada Zon:',
    uploadingBtn: 'Memuat naik...',
    selectUploadBtn: 'Pilih & Muat Naik Fail CSV / Excel',
    listView: 'Paparan Senarai',
    loadingParts: 'Memuatkan bahagian...',
    material: 'Bahan',
    partNo: 'No Bahagian',
    zone: 'Zon',
    location: 'Lokasi',
    status: 'Status',
    action: 'Tindakan',
    viewEdit: 'Lihat / Edit',
    noParts: 'Tiada bahagian dijumpai.',
    countingInterface: 'Antara Muka Kiraan',
    partInformation: 'Maklumat Bahagian',
    lock: 'Kunci',
    adminUnlockBtn: 'Buka Kunci Admin',
    counterInputs: 'Input Pengira',
    box: 'Kotak',
    boxTotal: 'Jumlah Kotak:',
    verifierInput: 'Input Pengesah',
    recountValue: 'Nilai Kiraan Semula',
    enterRecount: 'Masukkan jumlah kiraan semula...',
    recountWarning: '* Nilai kiraan semula TIDAK BOLEH sama dengan Jumlah Kotak.',
    saveData: 'Simpan Data',
    saving: 'Menyimpan...',
    userProgressReport: 'Laporan Kemajuan Pengguna',
    downloadPdf: 'Muat Turun PDF',
    progressSummary: 'Kiraan Stok VGM - Ringkasan Kemajuan',
    recentActivity: 'Aktiviti Terkini',
    loadingData: 'Memuatkan data...',
    lastUpdated: 'Kemas Kini Terakhir',
    showingLatestUpdates: 'Laporan dijana pada',
    dataRefreshed: 'Data berjaya disegarkan!',
    downloadCsv: 'Muat Turun CSV',
    userSummary: 'Ringkasan Pengguna',
    name: 'Nama',
    lastLogin: 'Log Masuk Terakhir',
    lastLogout: 'Log Keluar Terakhir',
    filterByStatus: 'Tapis ikut Status',
    filterByLocation: 'Tapis ikut Lokasi',
    allStatuses: 'Semua Status',
    allLocations: 'Semua Lokasi',
    generatedOn: 'Dijana pada',
    verifiedBy: 'Disahkan Oleh',
    itemDetails: 'Butiran Item',
    edit: 'Sunting',
    unlock: 'Buka Kunci',
    locked: 'Terkunci',
    save: 'Simpan',
    itemInformation: 'Maklumat Item',
    countData: 'Data Kiraan',
    verifyNow: 'Sahkan Sekarang',
    addRemarkPlaceholder: 'Klik untuk tambah catatan...',
    // Redesign
    refresh: 'Muat Semula',
    live: 'Langsung',
    dashboard: 'Papan Pemuka',
    admin: 'Admin',
    users: 'Pengguna',
    all: 'Semua',
    total: 'Jumlah',
    qty: 'Kuantiti',
    soon: 'Akan datang',
    noData: 'Tiada data',
    checkPart: 'Semak Bahagian',
    partsFlagged: 'bahagian ditanda untuk semakan semula',
    partsVerified: 'Bahagian disahkan',
    partsToCheck: 'Bahagian untuk disemak',
    adminTools: 'Alat admin',
    uploadParts: 'Muat naik bahagian',
    tapZoneHint: 'Ketik zon untuk mula mengira',
    showingRange: 'Memaparkan {range} daripada {total}',
    zoneNotUploaded: 'Belum ada bahagian dimuat naik untuk {zone}. Admin boleh memuat naiknya di Admin → Muat naik bahagian.',
    latestUpload: 'Muat naik terkini',
    oldUpload: 'Muat naik lama',
    nextBoxHint: 'Kotak seterusnya muncul selepas kotak ini diisi',
    recount: 'Kiraan Semula',
    verifierOnly: 'Pengesah sahaja',
    matchesBoxTotal: 'Sepadan dengan jumlah kotak ({n})',
    differsBoxTotal: 'Berbeza daripada jumlah kotak ({n})',
    enterCountToSave: 'Masukkan kiraan untuk simpan',
    forgotPassword: 'Lupa kata laluan? Hubungi admin anda.',
    installApp: 'Pasang aplikasi',
    loginTagline: 'Jabatan Logistik CKD — inventori kilang untuk B17, B22, LOMA dan B22 SEQ.',
    headline1: 'Kira.',
    headline2: 'Semak.',
    headline3: 'Sahkan.',
    // Parts upload
    partsUploadTab: 'Muat naik bahagian',
    zoneLocksNote: 'Zon dikunci sebaik sahaja ia mempunyai data.',
    selectFile: 'Pilih fail',
    fileTypesHint: '.csv, .xlsx atau .xls · maks 15MB',
    hasData: 'Ada data',
    emptyReady: 'Kosong · sedia',
    checkingZone: 'Menyemak status zon...',
    readingFile: 'Membaca fail...',
    previewTitle: 'Semak sebelum muat naik',
    rowsFound: '{n} baris',
    columnsFound: 'Lajur ditemui',
    missingColumns: 'Lajur tiada',
    missingRequired: 'Tiada {cols} — senarai bahagian zon ini memerlukannya.',
    missingBoxes: 'Tiada lajur Box — pengira tidak dapat memasukkan kiraan.',
    missingRecount: 'Tiada lajur Recount — pengesah tidak akan ada kotak kiraan semula.',
    zoneMismatch: 'Nama fail menyatakan {fileZone}, tetapi anda memilih {selZone}. Ke mana ia patut pergi?',
    targetLocked: '{zone} sudah mempunyai data. Buka kunci & kosongkan dahulu, atau pilih zon lain.',
    uploadTo: 'Muat naik ke {zone}',
    chooseOtherFile: 'Pilih fail lain',
    fileTableNote: 'Jadual dijana daripada tajuk lajur fail anda.',
    fileNameNote: 'Namakan fail dengan zonnya (cth. VGM 2026 - B22.xlsx) dan ia akan dicadangkan secara automatik.',
    zoneIsLocked: '{zone} dikunci',
    lockedExplain: 'Zon ini sudah mempunyai jadual pangkalan data. Untuk memuat naik fail induk baharu, buka kunci dan kosongkannya dahulu.',
    unlockClear: 'Buka kunci & kosongkan zon',
    unlockTitle: 'Buka kunci & kosongkan {zone}',
    unlockWarn: 'Ini memadam secara kekal semua bahagian, kiraan dan catatan dalam {zone}. Fail sandaran dimuat turun dahulu.',
    typeToConfirm: 'Taip {code} untuk sahkan',
    backupAndClear: 'Muat turun sandaran & kosongkan',
    backingUp: 'Menyimpan sandaran...',
    backupFailed: 'Sandaran gagal, jadi tiada apa yang dipadam: {err}',
    zoneCleared: '{zone} telah dikosongkan. Sandaran disimpan sebagai {file}.',
    offline: 'Luar talian',
    toSync: '{n} untuk disegerak',
    syncedCounts: '{n} kiraan tersimpan telah disegerak',
    syncFailed: '{n} tidak dapat disimpan — ketik untuk cuba lagi',
    savedOffline: 'Tiada isyarat — disimpan dalam telefon ini. Ia akan disegerak apabila anda kembali dalam talian.',
    showingCached: 'Tiada isyarat — memaparkan data yang dimuat sebelum ini.',
    lastUpdate: 'Kemas kini terakhir'
  },
  DE: {
    login: 'Anmelden',
    userId: 'Benutzer-ID',
    password: 'Passwort',
    hub: 'Kommandozentrale',
    stockTake: 'Inventur',
    batteryTracking: 'Batterieverfolgung',
    qualityAssurance: 'Qualitätssicherung',
    back: 'Zurück',
    notCounted: 'Nicht gezählt',
    counted: 'Gezählt',
    verified: 'Verifiziert',
    role: 'Rolle',
    zoneProgress: 'Zonenfortschritt',
    search: 'Teilenr. / Material suchen...',
    welcome: 'Willkommen',
    selectModule: 'Wählen Sie ein Modul, um fortzufahren',
    manageParts: 'Verwalten Sie den Teilebestand, die Zählungen und die zonenübergreifende Verifizierung.',
    trackBattery: 'Verfolgen Sie Batteriestatus, Standorte und Lebenszyklus.',
    overallProgress: 'Gesamtfortschritt',
    trackedToday: 'Heute erfasst',
    today: 'Heute',
    yourModules: 'Ihre Module',
    performQA: 'Führen Sie QA-Inspektionen durch und protokollieren Sie Abweichungen.',
    uploadRawCsv: 'Rohe CSV-Daten hochladen',
    uploadRawCsvDesc: 'CSV-Dateien automatisch in Supabase hochladen. Neue Spalten werden automatisch hinzugefügt.',
    selectData: 'Daten auswählen',
    loggedInAs: 'Angemeldet als',
    logout: 'Abmelden',
    view: 'ANSICHT',
    liveData: 'Live-Daten',
    items: 'Artikel',
    ready: 'Bereit',
    pending: 'Ausstehend',
    zones: 'Zonen',
    progress: 'Fortschritt',
    userProgress: 'Benutzerfortschritt',
    viewCheckPart: 'Prüfteildaten anzeigen (Anmerkungen)',
    adminSettingsCsv: 'Admin-Einstellungen (CSV-Upload)',
    confirmLogout: 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    cancel: 'Abbrechen',
    rememberMe: 'Angemeldet bleiben',
    adminSettings: 'Admin-Einstellungen',
    masterPartsDbUpload: 'Master-Teiledatenbank-Upload',
    uploadDesc: 'Laden Sie eine .xlsx-Datei hoch, um den Teilebestand zu aktualisieren.',
    fileRequirements: 'Dateianforderungen:',
    formatLabel: 'Format: .csv, .xlsx oder .xls',
    requiredColumns: 'Erforderliche Spalten: Material, Teilename (oder Teilenummer), Lagerplatz (oder Standort)',
    extraColumns: 'Alle zusätzlichen Spalten werden automatisch im Metadatenfeld der Datenbank gespeichert!',
    assignZone: 'Zone zuweisen:',
    uploadingBtn: 'Wird hochgeladen...',
    selectUploadBtn: 'CSV / Excel-Datei auswählen & hochladen',
    listView: 'Listenansicht',
    loadingParts: 'Lade Teile...',
    material: 'Material',
    partNo: 'Teile-Nr.',
    zone: 'Zone',
    location: 'Standort',
    status: 'Status',
    action: 'Aktion',
    viewEdit: 'Anzeigen / Bearbeiten',
    noParts: 'Keine Teile gefunden.',
    countingInterface: 'Zähloberfläche',
    partInformation: 'Teileinformationen',
    lock: 'Sperren',
    adminUnlockBtn: 'Admin-Entsperrung',
    counterInputs: 'Zählereingaben',
    box: 'Karton',
    boxTotal: 'Kartongesamt:',
    verifierInput: 'Prüfereingabe',
    recountValue: 'Nachzählwert',
    enterRecount: 'Nachzählsumme eingeben...',
    recountWarning: '* Nachzählwert darf NICHT der Kartongesamtsumme entsprechen.',
    saveData: 'Daten speichern',
    saving: 'Speichern...',
    userProgressReport: 'Benutzerfortschrittsbericht',
    downloadPdf: 'PDF herunterladen',
    progressSummary: 'VGM-Inventur - Fortschrittszusammenfassung',
    recentActivity: 'Letzte Aktivität',
    loadingData: 'Daten werden geladen...',
    lastUpdated: 'Zuletzt aktualisiert',
    showingLatestUpdates: 'Bericht erstellt am',
    dataRefreshed: 'Daten erfolgreich aktualisiert!',
    downloadCsv: 'CSV herunterladen',
    userSummary: 'Benutzerübersicht',
    name: 'Name',
    lastLogin: 'Letzter Login',
    lastLogout: 'Letzter Logout',
    filterByStatus: 'Nach Status filtern',
    filterByLocation: 'Nach Standort filtern',
    allStatuses: 'Alle Status',
    allLocations: 'Alle Standorte',
    generatedOn: 'Erstellt am',
    verifiedBy: 'Überprüft von',
    itemDetails: 'Artikeldetails',
    edit: 'Bearbeiten',
    unlock: 'Entsperren',
    locked: 'Gesperrt',
    save: 'Speichern',
    itemInformation: 'Artikelinformationen',
    countData: 'Zähldaten',
    verifyNow: 'Jetzt Bestätigen',
    addRemarkPlaceholder: 'Klicken Sie, um eine Bemerkung hinzuzufügen...',
    // Redesign
    refresh: 'Aktualisieren',
    live: 'Live',
    dashboard: 'Dashboard',
    admin: 'Admin',
    users: 'Benutzer',
    all: 'Alle',
    total: 'Gesamt',
    qty: 'Menge',
    soon: 'Bald',
    noData: 'Keine Daten',
    checkPart: 'Teil prüfen',
    partsFlagged: 'Teile zur Nachprüfung markiert',
    partsVerified: 'Teile bestätigt',
    partsToCheck: 'Zu prüfende Teile',
    adminTools: 'Admin-Werkzeuge',
    uploadParts: 'Teile hochladen',
    tapZoneHint: 'Zone antippen, um zu zählen',
    showingRange: 'Zeige {range} von {total}',
    zoneNotUploaded: 'Für {zone} wurden noch keine Teile hochgeladen. Ein Admin kann sie unter Admin → Teile hochladen hochladen.',
    latestUpload: 'Neuester Upload',
    oldUpload: 'Älterer Upload',
    nextBoxHint: 'Die nächste Box erscheint, sobald diese ausgefüllt ist',
    recount: 'Nachzählung',
    verifierOnly: 'Nur Prüfer',
    matchesBoxTotal: 'Stimmt mit Box-Summe überein ({n})',
    differsBoxTotal: 'Weicht von Box-Summe ab ({n})',
    enterCountToSave: 'Zum Speichern Menge eingeben',
    forgotPassword: 'Passwort vergessen? Fragen Sie Ihren Admin.',
    installApp: 'App installieren',
    loginTagline: 'CKD-Logistikabteilung — Werksinventur für B17, B22, LOMA und B22 SEQ.',
    headline1: 'Zählen.',
    headline2: 'Prüfen.',
    headline3: 'Bestätigen.',
    // Parts upload
    partsUploadTab: 'Teile hochladen',
    zoneLocksNote: 'Eine Zone wird gesperrt, sobald sie Daten enthält.',
    selectFile: 'Datei wählen',
    fileTypesHint: '.csv, .xlsx oder .xls · max. 15 MB',
    hasData: 'Hat Daten',
    emptyReady: 'Leer · bereit',
    checkingZone: 'Zonenstatus wird geprüft...',
    readingFile: 'Datei wird gelesen...',
    previewTitle: 'Vor dem Hochladen prüfen',
    rowsFound: '{n} Zeilen',
    columnsFound: 'Gefundene Spalten',
    missingColumns: 'Fehlende Spalten',
    missingRequired: '{cols} fehlt — die Teileliste dieser Zone benötigt es.',
    missingBoxes: 'Keine Box-Spalten — Zähler können keine Mengen eingeben.',
    missingRecount: 'Keine Recount-Spalte — Prüfer haben kein Nachzählfeld.',
    zoneMismatch: 'Der Dateiname nennt {fileZone}, ausgewählt ist aber {selZone}. Wohin soll sie?',
    targetLocked: '{zone} hat bereits Daten. Zuerst entsperren & leeren oder eine andere Zone wählen.',
    uploadTo: 'Nach {zone} hochladen',
    chooseOtherFile: 'Andere Datei wählen',
    fileTableNote: 'Die Tabelle wird aus den Spaltenüberschriften Ihrer Datei erstellt.',
    fileNameNote: 'Benennen Sie die Datei nach ihrer Zone (z. B. VGM 2026 - B22.xlsx), dann wird sie automatisch vorgeschlagen.',
    zoneIsLocked: '{zone} ist gesperrt',
    lockedExplain: 'Diese Zone hat bereits eine Datenbanktabelle. Zum Hochladen einer neuen Stammdatei zuerst entsperren und leeren.',
    unlockClear: 'Zone entsperren & leeren',
    unlockTitle: '{zone} entsperren & leeren',
    unlockWarn: 'Dies löscht dauerhaft alle Teile, Zählungen und Bemerkungen in {zone}. Zuerst wird eine Sicherungsdatei heruntergeladen.',
    typeToConfirm: 'Zum Bestätigen {code} eingeben',
    backupAndClear: 'Sicherung laden & leeren',
    backingUp: 'Sicherung wird gespeichert...',
    backupFailed: 'Sicherung fehlgeschlagen, daher wurde nichts gelöscht: {err}',
    zoneCleared: '{zone} wurde geleert. Sicherung gespeichert als {file}.',
    offline: 'Offline',
    toSync: '{n} zu synchronisieren',
    syncedCounts: '{n} gespeicherte Zählungen synchronisiert',
    syncFailed: '{n} konnten nicht gespeichert werden — zum Wiederholen tippen',
    savedOffline: 'Kein Signal — auf diesem Telefon gespeichert. Wird synchronisiert, sobald Sie wieder online sind.',
    showingCached: 'Kein Signal — zuvor geladene Daten werden angezeigt.',
    lastUpdate: 'Letzte Änderung'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  // t() with {placeholder} substitution, e.g. tf('uploadTo', { zone: 'B17' })
  tf: (key: string, vars: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('vgm_language') as Language) || 'EN';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('vgm_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations.EN[key] || key;
  };

  const tf = (key: string, vars: Record<string, string | number>) =>
    t(key).replace(/\{(\w+)\}/g, (m, name) => (name in vars ? String(vars[name]) : m));

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tf }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
